'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { CalendarDays, ChevronDown, ChevronUp, ListMusic, Pencil, Plus, Trash2, X } from 'lucide-react';
import type { Setlist, Song } from '@/types/song';
import { createSetlist, deleteSetlist, subscribeSetlists, updateSetlist } from './setlist-service';

export function SetlistsView({uid,songs}:{uid:string;songs:Song[]}) {
 const [items,setItems]=useState<Setlist[]>([]),[editing,setEditing]=useState<Setlist|null|'new'>(null),[error,setError]=useState('');
 useEffect(()=>subscribeSetlists(uid,setItems,e=>setError(e.message)),[uid]);
 return <div className="animate-rise"><div className="mb-8 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-muted">Performance plans</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">셋리스트</h1><p className="mt-2 text-muted">공연과 예배의 곡 순서를 미리 준비하세요.</p></div><button onClick={()=>setEditing('new')} className="flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-bold text-white"><Plus size={18}/>새 셋리스트</button></div>{error&&<p className="mb-4 text-sm text-red-600">{error}</p>}
 {items.length===0?<div className="grid min-h-80 place-items-center rounded-[24px] border border-line bg-white text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-lime"><ListMusic/></span><h2 className="mt-5 text-xl font-bold">아직 셋리스트가 없어요</h2><p className="mt-2 text-sm text-muted">첫 무대를 위한 곡 순서를 만들어 보세요.</p></div></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} onDoubleClick={()=>setEditing(item)} className="group rounded-[22px] border border-line bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-soft"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-canvas"><ListMusic size={20}/></span><div className="flex gap-1 opacity-100 md:opacity-0 md:group-hover:opacity-100"><button onClick={()=>setEditing(item)} title="수정" className="rounded-lg p-2 text-muted hover:bg-lime hover:text-ink"><Pencil size={17}/></button><button onClick={()=>confirm('셋리스트를 삭제할까요?')&&deleteSetlist(uid,item)} title="삭제" className="rounded-lg p-2 text-muted hover:bg-red-50 hover:text-red-600"><Trash2 size={17}/></button></div></div><button onClick={()=>setEditing(item)} className="block w-full text-left"><h2 className="mt-6 text-xl font-bold">{item.title}</h2><p className="mt-1 text-sm text-muted">{item.eventName||'행사 이름 없음'}</p><div className="mt-5 flex items-center justify-between border-t border-line pt-4 text-xs text-muted"><span className="flex items-center gap-1.5"><CalendarDays size={14}/>{item.eventDate||'날짜 미정'}</span><b className="text-ink">{item.songIds.length}곡</b></div></button></article>)}</div>}
 {editing&&<SetlistEditor uid={uid} songs={songs} item={editing==='new'?null:editing} onClose={()=>setEditing(null)}/>}</div>;
}

function SetlistEditor({uid,songs,item,onClose}:{uid:string;songs:Song[];item:Setlist|null;onClose:()=>void}){
 const [title,setTitle]=useState(item?.title??''),[eventName,setEventName]=useState(item?.eventName??''),[eventDate,setEventDate]=useState(item?.eventDate??''),[selected,setSelected]=useState<string[]>(item?.songIds??[]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const values={title:title.trim(),eventName:eventName.trim(),eventDate,songIds:selected};if(item)await updateSetlist(uid,item,values);else await createSetlist(uid,values.title,values.eventName,values.eventDate,values.songIds);onClose();}catch(reason){setError(reason instanceof Error?reason.message:'저장하지 못했습니다.');setBusy(false);}}
 function toggle(id:string){setSelected(value=>value.includes(id)?value.filter(songId=>songId!==id):[...value,id]);}
 function move(index:number,direction:-1|1){setSelected(value=>{const target=index+direction;if(target<0||target>=value.length)return value;const copy=[...value];[copy[index],copy[target]]=[copy[target],copy[index]];return copy;});}
 const selectedSongs=selected.map(id=>songs.find(song=>song.id===id)).filter((song):song is Song=>!!song);
 return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/50 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><form onSubmit={submit} className="flex max-h-[92vh] w-full max-w-2xl flex-col overflow-hidden rounded-[28px] bg-white shadow-soft animate-rise"><header className="flex items-center justify-between border-b border-line px-7 py-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">Setlist editor</p><h2 className="mt-1 text-2xl font-bold">{item?'셋리스트 수정':'새 셋리스트'}</h2></div><button type="button" disabled={busy} onClick={onClose} className="rounded-full p-2 hover:bg-canvas"><X/></button></header><div className="overflow-y-auto p-7"><div className="grid gap-4 sm:grid-cols-2"><Input label="제목" value={title} set={setTitle} required/><Input label="행사" value={eventName} set={setEventName}/><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">날짜</span><input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)} className="w-full rounded-xl border border-line px-4 py-3 outline-none focus:border-ink"/></label></div>
 <div className="mt-7 grid gap-5 md:grid-cols-2"><section><p className="mb-2 text-sm font-bold">라이브러리 <span className="font-normal text-muted">({songs.length}곡)</span></p><div className="max-h-64 overflow-auto rounded-xl border border-line">{songs.length===0?<p className="p-4 text-sm text-muted">라이브러리에 곡을 먼저 추가해 주세요.</p>:songs.map(song=><label key={song.id} className="flex cursor-pointer items-center gap-3 border-b border-line px-4 py-3 last:border-0 hover:bg-canvas"><input type="checkbox" checked={selected.includes(song.id)} onChange={()=>toggle(song.id)}/><span className="min-w-0 truncate text-sm font-bold">{song.title}</span></label>)}</div></section><section><p className="mb-2 text-sm font-bold">연주 순서 <span className="font-normal text-muted">({selected.length}곡)</span></p><div className="max-h-64 overflow-auto rounded-xl border border-line">{selectedSongs.length===0?<p className="p-4 text-sm text-muted">왼쪽에서 곡을 선택하세요.</p>:selectedSongs.map((song,index)=><div key={song.id} className="flex items-center gap-2 border-b border-line px-3 py-2 last:border-0"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-canvas text-xs font-bold">{index+1}</span><span className="min-w-0 flex-1 truncate text-sm font-bold">{song.title}</span><div className="flex"><button type="button" disabled={index===0} onClick={()=>move(index,-1)} className="p-1 text-muted disabled:opacity-20"><ChevronUp size={16}/></button><button type="button" disabled={index===selectedSongs.length-1} onClick={()=>move(index,1)} className="p-1 text-muted disabled:opacity-20"><ChevronDown size={16}/></button><button type="button" onClick={()=>toggle(song.id)} className="p-1 text-muted hover:text-red-600"><X size={16}/></button></div></div>)}</div></section></div>{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}</div><footer className="flex justify-end gap-2 border-t border-line bg-canvas px-7 py-5"><button type="button" onClick={onClose} className="px-4 py-3 text-sm font-bold">취소</button><button disabled={busy||!title.trim()} className="rounded-xl bg-ink px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{busy?'저장 중…':item?'변경 저장':'만들기'}</button></footer></form></div>;
}
function Input({label,value,set,required=false}:{label:string;value:string;set:(v:string)=>void;required?:boolean}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><input required={required} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border border-line px-4 py-3 outline-none focus:border-ink"/></label>}
